// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MonikerManifestTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "d5ed0bf3-4e8d-4199-b1ff-6c271e08bd0b";
        public const string Name = "Image Manifest Tools";
        public const string Description = @"Makes it easier to create and maintain .imagemanifest files for Visual Studio extension";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "image, manifest, vsix";
    }
}
