// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MonikerManifestTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "04f92311-4748-4f87-9d94-1aae42483d1f";
        public const string Name = "Image Manifest Tools";
        public const string Description = @"Makes it easier to create and maintain .imagemanifest files for Visual Studio extension";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "image, manifest, vsix";
    }
}
