// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MonikerManifestTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "cfcd9783-7294-4253-8667-7f685139857a";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidVsixProjectString = "a5d207b6-3782-4c7b-8010-6cec051c2520";
        public static Guid guidVsixProject = new Guid(guidVsixProjectString);

        public const string guidPackageCmdSetString = "7079c532-705a-40f6-bb4a-360c9bb5f8e6";
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CreateManifest = 0x0100;
    }
}